language: java
jdk:
- oraclejdk7
- openjdk6
notifications:
  slack:
    secure: nSYz9U1N/Ejodb/vxHjK8RkCjyTlGxxiZVKSVsAfhq6CRzjtWT0jKw1jyt9Iv5nE3gV30jhLdYBj3QQcw98N/ZFQ0KbVrEocgRj0pTXx2w6bvU9Dr5N+b82ZE484f8m5TYI3e06Xan2lSMRRIzyxMEqRW9I73crNxvuI3ZXdZSg=
